# SDE parameters
sde:
  name: cell
  X_dim: 2
  W_dim: 2
  T: 5.0
  dt: 1.0e-2
  t_scheme: linear
  params_X_unc:
    alpha: 0.0625 
    sigma: 0.1
  params_X_aux:
    alpha: 0.0625
    sigma: 0.1
  u: ["-1.0", "-1.0"]
  v: ["-1.0", "-1.0"]
  eps: 1.0e-10

# network parameters
network:
  mlp_type: mlp_small
  out_dim: 2
  hidden_dims: [32, 32, 32, 32]
  activation: tanh
  normalization_type: null
  dropout_rate: 0.4

# Training parameters
training:
  save_name: cell_multimode
  learning_rate: 1.0e-3
  batch_size: 20
  n_iters_per_epoch: 500
  n_epochs: 15
  ema_decay: 0.995
  optimizer: adam
  warmup_steps_ratio: 0.0
  clip_norm: 1.0

# MCMC parameters
mcmc:
  eta: 0.9
  n_chains: 1
  n_iters: 10000
  n_burn_in: 4000