# SDE parameters
sde:
  dim: 2
  T: 4.0
  dt: 1.0e-2
  params_X:
    alpha: 0.0625 
    sigma: 0.1
  params_X_tilde:
    alpha: 0.0625
    sigma: 0.1
  u: ["0.1", "-0.1"]
  v: ["2.0", "-0.1"]
  eps: 1.0e-10

# network parameters
network:
  mlp_type: "mlp_small"
  out_dim: 2
  hidden_dims: [20, 20, 20, 20]
  activation: "tanh"

# Training parameters
training:
  save_name: "cell_model_normal_sigma0.1"
  learning_rate: 5.0e-4
  batch_size: 64
  n_iters: 500
  n_epochs: 10
  ema_decay: 0.995
  optimizer: "adam"
  warmup_steps: 500
  clip_norm: 1.0