# SDE parameters
sde:
  T: 5.0
  dt: 0.01
  N: 400
  alpha: 0.0625
  sigma: 0.1
  u: ["-1.0", "-1.0"]
  v: ["-1.0", "-1.0"]

# network parameters
network:
  output_dim: 2
  time_embedding_dim: 32
  init_embedding_dim: 16
  activation: "leaky_relu"
  encoder_layer_dims: [16]
  decoder_layer_dims: [128, 128]

# training parameters
training:
  v: null
  batch_size: 100
  epochs_per_load: 1
  lr: 1e-2
  num_reloads: 100
  load_size: 100_000