# SDE parameters
sde:
  n_landmarks: 32
  T: 1.0
  dt: 0.01
  dim: null
  params_X:
    k_alpha: 0.3
    k_sigma: 0.5
    n_landmarks: 32
    m_landmarks: 2
  params_X_tilde:
    k_alpha: 0.3
    k_sigma: 0.5
    n_landmarks: 32
    m_landmarks: 2
  u:
    n_landmarks: 32
    a: 1.0
    b: 0.5
    rotation: 0.0
    shift_x: 0.0
    shift_y: 0.0
  v:
    n_landmarks: 32
    a: 1.0
    b: 0.5
    rotation: 1.04719753333 # pi / 3 
    shift_x: -1.0
    shift_y: 0.5
  eps: 1.0e-3

# network parameters
network:
  mlp_type: "mlp_large"
  out_dim: 64
  encoder_dims: [64]
  decoder_dims: [256, 128, 128]
  t_emb_dim: 32
  t_emb_max_period: 100.0
  t_emb_scaling: 100.0
  activation: "tanh"

# Training parameters
training:
  save_name: "landmark_ellipse_32"
  learning_rate: 7.0e-4
  batch_size: 16
  n_iters: 1500
  n_epochs: 20
  ema_decay: 0.995
  optimizer: "adam"
  warmup_steps: 1500
  clip_norm: 1.0